# Generated by Django 4.1.4 on 2022-12-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_friendship_updated_at"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friendship",
            name="unique_booking",
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("follower", "followee"), name="unique_followship"
            ),
        ),
    ]
