# Generated by Django 4.1.2 on 2022-11-07 06:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tweet",
            options={"verbose_name_plural": "ツイート"},
        ),
        migrations.AlterField(
            model_name="tweet",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
