# Generated by Django 4.1.2 on 2022-11-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_alter_tweet_options_alter_tweet_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tweet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
