# Generated by Django 4.1.4 on 2023-01-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tweets", "0002_favorite"),
        ("tweets", "0002_favorite_favorite_unique_favorite"),
    ]

    operations = []
